### ISSUE TITLE
What happens if I run Aegis on Windows 10?

### ISSUE THREAD

**Issue by alopezf1987** [th3power/aegis-voat#2]
Hi,

I wanted to launch it on a Windows 7 SP1 machine but accidentally, I ran it on my own computer. What effects may it have over my Windows 10 PC?

Thanks in advance.

**Comment by th3power** [comment]
I don't have a way to test it so I'm just guessing, but it probably would not break anything. Most commands will probably fail due to missing executables, incorrect registry paths, etc. The host blocks would probably still work but you can reverse those with the unblock script. Let me know if you have a specific problem or question.
