### ISSUE TITLE
Is KB3118401 safe?

### ISSUE THREAD

**Issue by BItim** [th3power/aegis-voat#3]
Is "[Update for Universal C Runtime in Windows](https://support.microsoft.com/en-us/kb/3118401)"?
The description of this update:

> The Windows 10 Universal CRT is a Windows operating system component that enables CRT functionality on the Windows operating system. This update allows Windows desktop applications that depend on the Windows 10 Universal CRT release to run on earlier Windows operating systems.
> 
> Microsoft Visual Studio 2015 creates a dependency on the Universal CRT when applications are built by using the Windows 10 Software Development Kit (SDK). You can install this update on earlier Windows operating systems to enable these applications to run correctly.

Looks suspicious for me.

**Comment by Sarabveer** [comment]
It's a software dependency. You need it for programs built with the Win10 SDK.

**Comment by th3power** [comment]
Thanks for your feedback. The answer is yes it is safe (as far as we can tell, at least). It was initially blocked because we have no desire for any Windows 10 components or functionality, however we found that many users were negatively affected due to the dependency with Visual Studio. We reviewed it again and determined that it is harmless and so it was removed from the block list. If you have any evidence that suggests otherwise please let us know and we will gladly review and respond.
