### ISSUE TITLE
Is the inability to log into MSDN after running aegis.cmd intentional or by mistake?

### ISSUE THREAD

**Issue by assarbad** [th3power/aegis-voat#6]
Hi,

my question is already in the subject line. Turns out after applying `aegis.cmd` I can no longer log into MSDN. This only started with the version from about five days ago, but I hadn't updated before that for about a month. So somewhere in between this would have been introduced.

Thanks for the tool!

**Comment by th3power** [comment]
Not intentional... please let me know which host blocks are causing this issue for you and I will adjust them. You can do this in Chrome by right clicking on the pag, click inspect element, and click on console tab, the blocked hosts will be in red with an error message. 

Note: You can remove blocks by running unblock.cmd (right click, run as admin) however there may be some old leftover blocks that you may need to clear manually. You can do this by running "route -f" in an elevated console. You will have to release/renew your ip or disable/enable your network adapter afterwards.

**Comment by twerp** [comment]
MSDN login needs access to auth.gfx.ms.

**Comment by th3power** [comment]
That host was already removed from the block list in a previous version so this should no longer be an issue. Please use the latest version of aegis and if you still have this problem follow the steps above to clear old blocks. Note: You may also need to manually inspect the hosts file and remove any old blocks that are no longer tracked in the newer version (or you can run unblock from an older version). If you still have a problem please re-open this issue or make a new one.
