### ISSUE TITLE
I can not log in onedrive or other live.com pages

### ISSUE THREAD

**Issue by pitsi** [th3power/aegis-voat#8]
I can no longer log in onedrive after running aegis.cmd. It seems some relevant stuff was written in hosts, because I managed to log in once I (blindly) removed all extra lines from the hosts file.

Aegis 1.17 (now trying 1.18), windows 7 pro x64, chrome 51.x x64, chromium 53.x x64 (dev version).

(this is possibly a duplicate of issue #4...)

**Comment by Rabcor** [comment]
Have you tried firefox?

**Comment by pitsi** [comment]
It does work now. It may have been an issue on 1.17 or earlier, but it is solved in 1.18 as it seems. Tested on the above browsers, plus ie 11 and firefox as you suggested.
I forgot to mention that on the same pc which dual boots debian and windows 7, I had no issues under debian as well. I use chromium and firefox there.

**Comment by th3power** [comment]
Sorry I did not respond sooner. Aegis has not needed to be updated for a while so I haven't been monitoring this very closely. It is detailed in the README.md that we do indeed block onedrive/skydrive. This is detailed in issue #4 as you already mentioned and a workaround is offered there as well. However the issue you were having was likely due to an issue with incorrect host blocks on an older version of Aegis. This is probably why you were able to solve it by clearing the old host blocks. If you have a similar problem in the future you can clear/delete your hosts file, run 'route -f' in an elevated console, then run block.cmd (right click/run as admin) to make sure you are using only the latest blocks.
